### ISSUE TITLE
Add indentation rules for json body

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/restclient.el#2]
Try to use `json-mode` or `js-mode` in a separate buffer, format the string and copy it over.

**Comment by Fuco1** [comment]
This should be instead handled by using `edit-indirect-region`

**Comment by Fuco1** [comment]
https://github.com/pashky/restclient.el/issues/85#issuecomment-345768180

**Comment by Fuco1** [comment]
The upstream is not very keen on merging pull requests so I'm not going to bother.  Write a blog post instead, that will probably reach more people.

**Comment by pederkl** [comment]
Hi.  Current Melpa is based on [emacsorphanage/restclient](https://github.com/emacsorphanage/restclient/), which I maintain (forked from pashkys archived repo).  I'm working through the open issues in pashkys repository and came across this.  If you would like to send a pull request, I would be happy to accept it.  If not, I'll probably hack together something similar to what you posted in the comment on the original issue when I get around to it.

**Comment by Fuco1** [comment]
My code in the comment in the original repo uses edit-indirect package.  If you're ok with that dependency I think you can copy-paste the code and it will work right away. Otherwise that functionality would need to be duplicated somehow.

**Comment by pederkl** [comment]
Thanks.  I started work on this some time ago, but it's been a busy time lately, so I have not completed it, it still sits in a local branch of mine.  I can't quite remember where I left off, but I planned on making the dependency on edit-indirect be a soft one.  I don't want to force anyone to install edit-indirect, but if you don't, you don't get the functionality.  I hope to get some time to complete this reasonably soon.

**Comment by pederkl** [comment]
I had another look at the code tonight, and refreshed my memory.  The code I have (basically copied from your comment) sort of works; an indirect buffer is opened with the body of the request.  However, the indirect buffer is in fundamental-mode, not json-mode.  IMO that makes the feature rather poinless.  I ran out of time chasing down the rabbit hole of getting edit-indirect (or maybe Emacs in general) to recognize a json-buffer independently of the buffer name.

Do you have a trick for doing that, that you want to share?  Or do you turn on json-mode manually in the indirect buffer?  Do you think the feature is worth shipping even without automatically setting the mode in the indirect buffer, or at least documenting how to?
